image: node:latest

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

stages:
  - install
  - test
  - staging
  - production

install-dependencies:
  stage: install
  variables:
    CHROME_BIN: google-chrome
  script:
    - npm install
  artifacts:
    expire_in: 1hr
    paths:
      - node_modules/
  cache:
    paths:
      - node_modules/

staging:
  type: deploy
  stage: staging
  dependencies:
    - install-dependencies
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  only:
    - release

production:
  type: deploy
  stage: production
  dependencies:
    - install-dependencies
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - master
